// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Config {
    "trayMatchEnabled": boolean;
    "trayMatchTools": string[] | null;
    "urlTrayMatchMigrated": boolean;
    "autoOverwrite": boolean;
    "autoCheckUpdates": boolean;
    "language": string;
    "sidebarMode": string;
    "sidebarTools": SidebarToolConfig[] | null;
    "themeMode": string;
    "lightTheme": string;
    "darkTheme": string;
    "diffClipboardTargetMode": string;
    "codeEditorFontSize": number;
    "timeResultOrder": string[] | null;
    "hiddenTimeResults": string[] | null;
    "jsonAutoFormatOnFill": boolean;
    "jsonAutoFormatOnFillMigrated": boolean;
    "textAlwaysShowSearch": boolean;
    "dockerCLIPath": string;
    "imageSources": ImageSource[] | null;
    "sshProfilesVersion": number;
    "sshProfiles": SSHProfile[] | null;
    "fileSources": FileSource[] | null;
    "serviceTargets": ServiceTarget[] | null;
}

export interface DockerComposeGroup {
    "id": string;
    "name": string;
    "containers": DockerContainer[] | null;
}

export interface DockerContainer {
    "id": string;
    "name": string;
    "image": string;
    "status": string;
    "running": boolean;
    "createdAt": string;
    "ports": string[] | null;
    "labels": { [_ in string]?: string } | null;
    "composeProject"?: string;
    "composeService"?: string;
}

export interface DockerContainerDetail {
    "container": DockerContainer;
    "command": string[] | null;
    "entrypoint": string[] | null;
    "mounts": string[] | null;
    "networks": string[] | null;
    "restartPolicy": string;
}

export interface DockerDeleteFailure {
    "imageID": string;
    "error": string;
}

export interface DockerDeleteResult {
    "deleted": string[] | null;
    "failed": DockerDeleteFailure[] | null;
}

/**
 * DockerDeleteTarget 固定删除确认时看到的镜像及其 digest。
 */
export interface DockerDeleteTarget {
    "imageID": string;
    "expectedDigest"?: string;
}

export interface DockerHealthcheck {
    "test": string[] | null;
    "interval": string;
    "timeout": string;
    "startPeriod": string;
    "retries": number;
}

export interface DockerImage {
    "id": string;
    "name": string;
    "tags": string[] | null;
    "repository": string;
    "digest": string;
    "mediaType": string;
    "sizeType": string;
    "size": string;
    "sizeBytes": number;
    "createdAt": string;
}

export interface DockerImageBatchResult {
    "succeeded": string[] | null;
    "failed": DockerImageOperationFailure[] | null;
}

export interface DockerImageDetail {
    "id": string;
    "name": string;
    "tags": string[] | null;
    "size": number;
    "createdAt": string;
    "architecture": string;
    "os": string;
    "labels": { [_ in string]?: string } | null;
    "command": string[] | null;
    "entrypoint": string[] | null;
    "repository": string;
    "digest": string;
    "mediaType": string;
    "sizeType": string;
    "manifest": RegistryManifest | null;
    "index": RegistryIndex | null;
    "metadata": DockerImageMetadata;
    "layers": DockerImageLayer[] | null;
    "runtime": DockerRuntimeConfig;
    "rawManifest": string;
}

export interface DockerImageLayer {
    "size": number;
    "digest": string;
    "mediaType": string;
}

export interface DockerImageMetadata {
    "createdAt": string;
    "architecture": string;
    "os": string;
    "osVersion": string;
    "variant": string;
    "author": string;
    "dockerVersion": string;
    "container": string;
    "configDigest": string;
    "rootfsType": string;
    "diffIDs": string[] | null;
}

export interface DockerImageOperationFailure {
    "image": string;
    "error": string;
}

/**
 * DockerImageReferenceChange 描述一个镜像引用变更。Source 和 Target
 * 都是传给 Docker CLI 的独立镜像引用，不经过 shell 拼接。
 */
export interface DockerImageReferenceChange {
    "source": string;
    "target": string;
}

export interface DockerOperationResult {
    "success": boolean;
    "image": string;
    "output": string;
    "error": string;
}

export interface DockerRuntimeConfig {
    "user": string;
    "workingDir": string;
    "env": string[] | null;
    "exposedPorts": string[] | null;
    "volumes": string[] | null;
    "stopSignal": string;
    "shell": string[] | null;
    "command": string[] | null;
    "entrypoint": string[] | null;
    "healthcheck": DockerHealthcheck | null;
    "tty": boolean;
    "openStdin": boolean;
    "networkDisabled": boolean;
}

export interface DockerStatus {
    "available": boolean;
    "cliPath": string;
    "version": string;
    "error": string;
}

/**
 * FileSource 是 SSH 文件管理中的可浏览源；同一连接可被多个源引用。
 */
export interface FileSource {
    "id": string;
    "name": string;
    "sshProfileID": string;
    "defaultPath": string;
    "favoritePaths"?: string[] | null;
}

export interface FileTask {
    "id": string;
    "type": string;
    "sourceID": string;
    "status": string;
    "stage": string;
    "current"?: string;
    "target"?: string;
    "paths"?: string[] | null;
    "conflicts"?: string[] | null;
    "completed": number;
    "total": number;
    "files": number;
    "doneFiles": number;
    "error"?: string;
    "createdAt": string;
    "updatedAt": string;
}

export interface FileTaskSnapshot {
    "revision": number;
    "tasks": FileTask[] | null;
}

export interface HistoryContent {
    "input": string;
    "output": string;
}

export interface HistoryEntry {
    "tool": string;
    "action": string;
    "detail": string;
    "mode": string;
    "mediaType": string;
    "name": string;
    "bytes": number;
    "input": string;
    "output": string;
}

export interface HistoryFilter {
    "tool": string;
    "from": number;
    "to": number;
}

export interface HistoryItem {
    "id": number;
    "tool": string;
    "action": string;
    "detail": string;
    "at": string;
    "mode": string;
    "mediaType": string;
    "name": string;
    "bytes": number;
}

export interface HistoryPage {
    "items": HistoryItem[] | null;
    "total": number;
}

export interface ImageExportResult {
    "started": number;
    "snapshot": ImageTaskSnapshot;
}

export interface ImageSource {
    "id": string;
    "name": string;
    "kind": string;
    "sshProfileID": string;

    /**
     * 以下字段仅用于旧调用方的内存兼容；一次性配置清理时会从持久化 SSH 来源中移除。
     */
    "sshHost"?: string;
    "sshPort"?: number;
    "sshUsername"?: string;
    "sshPassword"?: string;
    "sshPrivateKey"?: string;
    "sshPrivateKeyPath"?: string;
    "sshKeyPassphrase"?: string;
    "registryURL": string;
    "registryUsername": string;
    "registryPassword": string;
}

export interface ImageTask {
    "id": string;
    "type": string;
    "sourceID": string;
    "imageID": string;
    "status": string;
    "stage": string;
    "completed": number;
    "total": number;
    "totalEstimated": boolean;
    "bytes": number;
    "error"?: string;
    "path"?: string;
    "createdAt": string;
    "updatedAt": string;
}

export interface ImageTaskSnapshot {
    "revision": number;
    "tasks": ImageTask[] | null;
}

export interface LogMonitor {
    "id": string;
    "targetID": string;
    "resource": ServiceResourceRef;
    "state": string;
    "error"?: string;
    "truncated": boolean;
}

export interface PM2Process {
    "id": string;
    "name": string;
    "status": string;
    "pid": number;
    "restarts": number;
    "uptime": number;
    "cpu": number;
    "memory": number;
    "script": string;
    "cwd": string;
    "interpreter": string;
}

export interface PM2ProcessDetail {
    "process": PM2Process;
}

export interface QueryLogBufferRequest {
    "monitorIDs": string[] | null;
    "filter": ServiceLogFilter;
}

export interface RegistryDescriptor {
    "mediaType": string;
    "digest": string;
    "size": number;
    "platform": RegistryPlatform | null;
}

export interface RegistryIndex {
    "schemaVersion": number;
    "mediaType": string;
    "manifests": RegistryDescriptor[] | null;
}

export interface RegistryManifest {
    "schemaVersion": number;
    "mediaType": string;
    "config": RegistryDescriptor;
    "layers": RegistryDescriptor[] | null;
}

export interface RegistryPlatform {
    "architecture": string;
    "os": string;
    "variant": string;
}

/**
 * RemoteDirectoryListing 是一次远程目录读取结果，Path 为实际列出的绝对路径。
 * 请求路径为空时 Path 为 SFTP 工作目录（通常是 SSH 登录目录），而不是 "/"。
 */
export interface RemoteDirectoryListing {
    "path": string;
    "entries": RemoteFileEntry[] | null;
}

export interface RemoteFileEntry {
    "name": string;
    "path": string;
    "isDir": boolean;
    "isSymlink": boolean;
    "size": number;
    "modifiedAt": string;
    "createdAt": string;
}

export interface RemoteFileOperationResult {
    "conflicts"?: string[] | null;
}

/**
 * SSHConfigHost 是 ~/.ssh/config 中可以直接交给系统 ssh 的 Host 别名。
 */
export interface SSHConfigHost {
    "alias": string;
}

/**
 * SSHConnection 是文件工具复用的 SSH 连接配置。文件源只引用 ID，避免重复保存凭据。
 */
export interface SSHConnection {
    "id": string;
    "name": string;
    "mode": string;
    "alias": string;
    "host": string;
    "port": number;
    "username": string;
    "password": string;
    "privateKey": string;
    "privateKeyPath": string;
    "keyPassphrase": string;
}

/**
 * SSHKnownHost 是应用内 known_hosts 中的一条可管理记录。
 */
export interface SSHKnownHost {
    "id": string;
    "hosts": string;
    "keyType": string;
    "publicKey": string;
    "fingerprint": string;
    "comment"?: string;
    "marker"?: string;
}

/**
 * SSHProfile 是应用全局复用的 SSH 连接配置。
 */
export interface SSHProfile {
    "id": string;
    "name": string;
    "origin": string;
    "originAlias": string;
    "host": string;
    "port": number;
    "username": string;
    "password": string;
    "privateKey": string;
    "privateKeyPath": string;
    "keyPassphrase": string;
    "originUpdatedAt": string;
}

export interface ServiceActionItemResult {
    "id": string;
    "name": string;
    "error"?: string;
}

export interface ServiceActionRequest {
    "targetID": string;
    "resource": ServiceResourceRef;
    "action": string;
}

export interface ServiceActionResult {
    "succeeded": ServiceActionItemResult[] | null;
    "failed": ServiceActionItemResult[] | null;
}

export interface ServiceInventory {
    "target": ServiceTarget;
    "docker": ServiceRuntimeStatus;
    "pm2": ServiceRuntimeStatus;
    "systemd": ServiceRuntimeStatus;
    "dockerGroups": DockerComposeGroup[] | null;
    "containers": DockerContainer[] | null;
    "pm2Processes": PM2Process[] | null;
    "systemUnits": SystemdUnit[] | null;
}

export interface ServiceLogFilter {
    "query": string;
    "regex": boolean;
    "caseSensitive": boolean;
    "streams": string[] | null;
}

export interface ServiceLogLine {
    "sequence": number;
    "monitorID": string;
    "runtime": string;
    "resourceID": string;
    "name": string;
    "timestamp"?: string;
    "receivedAt": string;
    "stream": string;
    "text": string;
}

export interface ServiceLogSnapshot {
    "lines": ServiceLogLine[] | null;
    "maxSequence": number;
    "truncated": boolean;
}

export interface ServiceResourceRef {
    "runtime": string;
    "id": string;
    "scope"?: string;
    "name"?: string;
}

export interface ServiceRuntimeStatus {
    "available": boolean;
    "error"?: string;
}

export interface ServiceTarget {
    "id": string;
    "name": string;
    "kind": string;
    "sshProfileID"?: string;
}

export interface SidebarToolConfig {
    "id": string;
    "enabled": boolean;
}

export interface StartLogMonitorsRequest {
    "targetID": string;
    "resources": ServiceResourceRef[] | null;
}

/**
 * SystemInfo 描述运行 TinkerKit 的操作系统环境。
 */
export interface SystemInfo {
    "os": string;
    "version": string;
    "arch": string;
}

export interface SystemdUnit {
    "id": string;
    "name": string;
    "description": string;
    "loadState": string;
    "activeState": string;
    "subState": string;
    "scope": string;
}

export interface SystemdUnitDetail {
    "unit": SystemdUnit;
    "mainPID": number;
    "execStart": string;
    "fragmentPath": string;
}
